# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/blog_pages',
                'doc_host': 'https://prasad209.github.io',
                'git_url': 'https://github.com/prasad209/blog_pages',
                'lib_path': 'blog_pages'},
  'syms': { 'blog_pages.blog_pages': {'blog_pages.blog_pages.foo': ('core.html#foo', 'blog_pages/blog_pages.py')},
            'blog_pages.core': {'blog_pages.core.foo': ('core.html#foo', 'blog_pages/core.py')}}}
